create table drinks
(
    id             bigint generated by default as identity not null,
    alcohol_volume double precision not null,
    created_at     timestamp        not null,
    deleted_at     timestamp        null,
    name           varchar(128)     not null,
    updated_at     timestamp        null,

    constraint pk_drinks primary key (id)
);

create table users
(
    id         bigint generated by default as identity not null,
    birth_date timestamp        null,
    created_at timestamp        not null,
    deleted_at timestamp        null,
    email      varchar(255) unique     null,
    sex        varchar(255)     null,
    updated_at timestamp        null,
    username   varchar(128)     null,
    weight     double precision null,

    constraint pk_users primary key (id)
);

create table pub_owners
(
    id         bigint generated by default as identity not null,
    created_at timestamp    not null,
    deleted_at timestamp    null,
    updated_at timestamp    null,
    bio        varchar(255) null,
    user_id    bigint       not null,

    constraint pk_pub_owners primary key (id),
    constraint FK_pub_owners_user_id foreign key (user_id) references users (id)
);

create table pubs
(
    id              bigint generated by default as identity not null,
    created_at      timestamp        not null,
    deleted_at      timestamp        null,
    latitude        double precision null,
    longitude       double precision null,
    name            varchar(128)     not null,
    updated_at      timestamp        null,
    city            varchar(255)     not null,
    country         varchar(255)     not null,
    postal_code     varchar(255)     not null,
    street          varchar(255)     not null,
    pub_owner_id    bigint           not null,

    constraint pk_pubs primary key (id),
    constraint FK_pubs_pub_owner_id foreign key (pub_owner_id) references pub_owners (id)
);

create table competitions
(
    id                  bigint generated by default as identity not null,
    title               varchar(128)    not null,
    description         varchar(300)    null,
    amount              integer         null,
    start_date_time     timestamp       null,
    end_date_time       timestamp       null,
    end_type            varchar(255)    not null,
    is_finished         boolean         not null,
    pub_id              bigint          null,
    owner_id            bigint          null,
    created_at          timestamp       not null,
    deleted_at          timestamp       null,
    updated_at          timestamp       null,

    constraint pk_competitions primary key (id),
    constraint FK_competitions_pub_id foreign key (pub_id) references pubs (id),
    constraint FK_competitions_owner_id foreign key (owner_id) references users (id)
);

create table competition_teams
(
    id             bigint generated by default as identity not null,
    created_at     timestamp    not null,
    deleted_at     timestamp    null,
    title          varchar(128) not null,
    updated_at     timestamp    null,
    competition_id bigint       null,

    constraint pk_competition_teams primary key (id),
    constraint FK_competition_teams_competition_id foreign key (competition_id) references competitions (id)
);

create table gatherings
(
    id              bigint generated by default as identity not null,
    created_at      timestamp       not null,
    deleted_at      timestamp       null,
    title           varchar(128)    not null,
    is_finished     boolean         not null,
    is_public       boolean         not null,
    updated_at      timestamp       null,
    pub_id          bigint          null,

    constraint pk_gatherings primary key (id),
    constraint FK_gatherings_pub_id foreign key (pub_id) references pubs (id)
);

create table pub_drinks
(
    id         bigint generated by default as identity not null,
    created_at timestamp        not null,
    deleted_at timestamp        null,
    volume     int              not null,
    price      double precision not null,
    updated_at timestamp        null,
    pub_id     bigint           null,
    drink_id   bigint           null,

    constraint pk_pub_drinks primary key (id),
    constraint FK_pub_drinks_drink_id foreign key (drink_id) references drinks (id),
    constraint FK_pub_drinks_pub_id foreign key (pub_id) references pubs (id)
);

create table competition_team_members
(
    id                  bigint generated by default as identity not null,
    created_at          timestamp             not null,
    deleted_at          timestamp             null,
    is_captain          boolean default false not null,
    updated_at          timestamp             null,
    competition_team_id bigint                null,
    user_id             bigint                null,

    constraint pk_competition_team_members primary key (id),
    constraint FK_competition_team_members_competition_team_id foreign key (competition_team_id) references competition_teams (id),
    constraint FK_competition_team_members_user_id foreign key (user_id) references users (id)
);

create table drank_drinks
(
    id               bigint generated by default as identity not null,
    drank_drink_type varchar(31) null,
    created_at       timestamp    not null,
    deleted_at       timestamp    null,
    updated_at       timestamp    null,
    pub_drink_id     bigint       null,
    user_id          bigint       null,
    competition_id   bigint       null,
    gathering_id     bigint       null,

    constraint pk_drank_drinks primary key (id),
    constraint FK_drank_drinks_competition_id foreign key (competition_id) references competitions (id),
    constraint FK_drank_drinks_gathering_id foreign key (gathering_id) references gatherings (id),
    constraint FK_drank_drinks_pub_drink_id foreign key (pub_drink_id) references pub_drinks (id),
    constraint FK_drank_drinks_user_id foreign key (user_id) references users (id)
);

create table gathering_members
(
    id           bigint generated by default as identity not null,
    approved     boolean default false null,
    created_at   timestamp             not null,
    deleted_at   timestamp             null,
    is_owner     boolean default false not null,
    updated_at   timestamp             null,
    gathering_id bigint                null,
    user_id      bigint                null,

    constraint pk_gathering_members primary key (id),
    constraint FK_gathering_members_gathering_id foreign key (gathering_id) references gatherings (id),
    constraint FK_gathering_members_user_id foreign key (user_id) references users (id)
);